### ISSUE TITLE
hangs at the base

### ISSUE THREAD

**Issue by rinnocenti** [ernieayala/ernies-modern-layout#6]
there must be other ways to execute this "bug", because there are times that are irreversible, and times that work, but it returns.
I couldn't get exact steps to reproduce the "irreversible" version but the other one is easy.
1. Open a tableroll
2. minimize the tableroll window (by clicking on the title).
3. Drag the mini window to the right.
It will open in a strange way and block at the bottom of the screen, (it is not possible to move it up for example).
but if you maximize it goes back to normal.
however if while it is minimized (buggy) and you open a new window, it already enters locked in the base being impossible to move it.

**Comment by rinnocenti** [comment]
FVTT 0.6.4

**Comment by ernieayala** [comment]
I think this should be fixed with 0.1.0 Release

**Comment by rinnocenti** [comment]
**it's better but it still happens.**

I try reproduce and i found a way.
1 - to compendium open a Item.
2 - Minimize the item window
3 - Drag & drop the minimized window to left (* it will open, maybe a bug *, minimize again)
4 - open a new item from compendium, and enter in "details" (or other option who enlarge the window at bottom like "file pick")
the window now fix in bottom.

other steps cause the bug eather (how to have more than one window minimized and open a new one, however the bug does not always appear like this but it happens.)
